### ISSUE TITLE
purge_api::purge_single_url is unable to purge a specified cache_url

### ISSUE THREAD

**Issue by dyro** [fastly/fastly-rust#1]
**Version**

fastly-api = "1.0.0-beta.0"

**What happened**

I'm unable to provide a `cached_url` value to the `PurgeSingleUrlParams` struct when calling the `purge_api::purge_single_url` function. It appears the implementation of `purge_signle_url` attempts to purge the [following URL instead](https://github.com/fastly/fastly-rust/blob/main/src/apis/purge_api.rs#L184): `<host>/*` 

**Expected Result**

The `PurgeSingleUrlParams` should allow the client to set the `cached_url` and the function `purge_single_url` should use the provided `cached_url` when constructing the url to purge. The docs [here](https://developer.fastly.com/reference/api/purging/#purge-single-url) indicate this is the expected behavior as well. 

Thanks for looking and many thanks for creating a rust sdk - it's much appreciated!

**Comment by chenrui333** [comment]
Any update on this thread?

**Comment by Integralist** [comment]
👋🏻 

I would recommend upgrading the version as there has been a couple of fixes related to purging since the original beta.

Refer to the [CHANGELOG](https://github.com/fastly/fastly-rust/blob/main/CHANGELOG.md) for details.

A big issue was resolved in 1.3.0 but there was also an authentication problem fixed in the earlier 1.2.0...

<img width="514" alt="Screenshot 2023-05-15 at 09 07 19" src="https://github.com/fastly/fastly-rust/assets/180050/1eeee85f-7b21-487b-bfea-7dd31e294e4c">

**Comment by Integralist** [comment]
https://github.com/fastly/fastly-rust/compare/release/v1.1.0...release/v1.3.0#diff-93e011e0356ff33d6d593b667125ca94efeee279937da85a4f230c4d1e0bd5a7

:point_up: The changes show...

1. We use the correct authentication type now (token, not basic auth)
2. We don't URL encode the path anymore (which was originally causing the API to error).
